### PR TITLE
Migrated to pathwatcher-without-runas

### LINKED ISSUE #43: installation on atom failed. OS: win8 64bit
Installing “markdown-preview-plus@1.5.0” failed.Hide output…

```
> runas@2.0.0 install C:\Users\Tal\AppData\Local\Temp\apm-install-dir-115514-2964-mqnnf4\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Tal\AppData\Local\Temp\apm-install-dir-115514-2964-mqnnf4\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Tal\AppData\Local\atom\app-0.209.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

> oniguruma@4.2.2 install C:\Users\Tal\AppData\Local\Temp\apm-install-dir-115514-2964-mqnnf4\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\Tal\AppData\Local\Temp\apm-install-dir-115514-2964-mqnnf4\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\Tal\AppData\Local\atom\app-0.209.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
gypgypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Tal\\AppData\\Local\\atom\\app-0.209.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Tal\\AppData\\Local\\atom\\app-0.209.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Tal\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Tal\\.atom\\.apmrc" "install" "C:\\Users\\Tal\\AppData\\Local\\Temp\\d-115514-2964-1l06avu\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

### PR DESCRIPTION
**Pull request by leipert**
should fix #43, #45 and #66.

reasoning behind this PR is in #67 

 @Galadirith, Could you test if this works on windows

### CODE REVIEW

**Comment by Galadirith** [comment]
@leipert Installed fine and all specs passing on Window 7 64 bit. Initially it didn't install but I think that was simply because I wasn't running a clean installation and `pathwatcher` was throwing up errors, [gist](https://gist.github.com/Galadirith/b84e5a0ef88df212f856) for reference.

**Comment by jonathandelgado** [comment]
I just tried this out and i'm getting a `pathwatcher` error similar to the gist. How did you resolve?

apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.10
git 1.9.5.msysgit.1
visual studio 2015

**Comment by Galadirith** [comment]
@jonathandelgado It seemed that the error was occurring for me because I had tried to `apm install` my local clone of this repo, however it was not a clean installation such that there was still the old `pathwatcher` module hanging around in `./node_modules`. Make sure that you have a clean clone of the repository and then try a `apm install` (it should be enough to simply delete `./node_modules`) and that resolved it for me.

If that's not working for you it would be really useful if you could post the command you are running and attach any errors (preferably as a gist), thanks @jonathandelgado.

**Comment by Galadirith** [comment]
@jonathandelgado just as an additional note `apm clean` is what I should have run before `apm install`, that would have removed any redundant modeuls, in this case `pathwatcher` :D

**Comment by jonathandelgado** [comment]
@Galadirith Glad you pinged this again, I didn't notice the original notification. I actually had the exact same thing, i'm just use to npm diffing automatically. Cleaned the modules and everything works fine now.

Thanks!

**Comment by SferaDev** [comment]
In my case now instead of missing runas, pops out missing pathwatcher-without-runas. Any input?

**Comment by Galadirith** [comment]
@SferaDev I'm sorry I'm slightly confused about the error, was it a CLI error while running `apm install` or a pop up red box error while running atom? If you could describe the steps you took to install the current HEAD of the MPP repo and where the error occurred and what it was. If its longer than a few lines it would be really helpful if you could post the error to a gist. Thanks @SferaDev

**Comment by SferaDev** [comment]
@Galadirith Sure, I cloned the current HEAD and manually apm install it. Then the same error that used to pop out with the runas package now appears with the pathwatcher-without-runas package. Could be something on my end though. I noticed that apm -v didn't show the version of VS and I'm reinstalling Visual Studio now. Python and other dependencies are up-to-date. When VS2015E finishes installing I'll tell you if the problem persists.

**Comment by Galadirith** [comment]
@SferaDev Ok great thanks so much for explaining, post back how it goes and hopefully all will be well, but if not we'll do some investigation.

**Comment by SferaDev** [comment]
Okay finally got it working. As I assumed the issue was VS, but it's weird. I have installed VS15 (14.0), VS13 (12.0) and VS12 (11.0) and neither VS15 or VS13 allowed me to install pathwatcher-without-runas either as a dependency on apm or directly from npm. But while forcing it to use version 11.0 namely VS2012 it passed the build.

Also I tried to install the original pathwatcher, the one that includes runas, through npm and forcing it to use VS12 it also compiled fine and didn't show the error everyone has been complaining of. 

So if anyone else encounters the runas/pathwatcher-without-runas/oniguruma issue use the --msvs_version=2012 flag while installing the dependencies through npm. My bet is that there's a missing lib on newer versions making it to only compile on <=2012 versions. Also you can force gyp to use 2012 with the environment variable GYP_MSVS_VERSION=2012.

See you!

**Comment by Galadirith** [comment]
@SferaDev Thanks for the info, really useful, glad its working :D

**Comment by leipert** [comment]
Thank you @SferaDev.

Do you think we should advice windows users to install VS12 and do the following install routine:

```
set GYP_MSVS_VERSION "2012"
apm install mathjax-wrapper markdown-preview-plus
```

**Comment by SferaDev** [comment]
@leipert At least a small advice on the install page would be appreciated.

**Comment by SferaDev** [comment]
Also #66 and #45 should be solved now with this extra step.

**Comment by leipert** [comment]
I am currently testing all combinations of VS here:
https://ci.appveyor.com/project/leipert/node-pathwatcher-without-runas/build/1.0.13
Oddly some of them did not fail in a prior test:
https://ci.appveyor.com/project/leipert/node-pathwatcher-without-runas/build/1.0.12
? ANY IDEAS?

**Comment by Galadirith** [comment]
@leipert Right now I'm running VS13 and it installs perfectly fine for me. 

I would be happy to add that as a suggestion to the [installation](https://github.com/Galadirith/markdown-preview-plus/blob/68ba18b16b1b37b2aafd1456ae7624a52377870f/docs/installation.md) docs page especially to highlight the VS flag options and environment variables which not everyone will know. 

But it would still seem that there are other factors we still haven't identified that cause these installation problems.

**Comment by leipert** [comment]
Another factor will definitly be the python version, as node-gyp needs python 2.7

**Comment by Galadirith** [comment]
> I am currently testing all combinations of VS

@leipert Awesome.

> Oddly some of them did not fail in a prior test? ANY IDEAS?

Yeh I don't have any suggestions right now as to why they're successfully building.

> Another factor will definitly be the python version, as node-gyp needs python 2.7

Definitely.

**Comment by SferaDev** [comment]
Maybe my VS13 installation didn't include some package that the VS12 did.

**Comment by leipert** [comment]
I found out how apm determines the VS version:
https://github.com/atom/apm/blob/b47423db2dd093404cab80d752793cdf91986111/src/apm.coffee#L91-L100

**Comment by leipert** [comment]
Pathwatcher withput runas seems to work with 2012 and 2013, 2008 and 2010 fail:
https://ci.appveyor.com/project/leipert/node-pathwatcher-without-runas/build/1.0.15

I will add tests to mpp which test it with 2012 and 2013

**Comment by Galadirith** [comment]
> Maybe my VS13 installation didn't include some package that the VS12 did

@SferaDev Thats definitely possible, with all of the different variant releases of different versions (express, re-distributable etc) different release do miss certain packages and libraries.

> I will add tests to mpp which test it with 2012 and 2013

Thats great thanks @leipert. 

I think with all of these subtly different errors usually the best source for solutions is [`node-gyp`](https://github.com/nodejs/node-gyp) who have updated VS versions in their README over the last year.

But adding suggestions to [installation](https://github.com/Galadirith/markdown-preview-plus/blob/68ba18b16b1b37b2aafd1456ae7624a52377870f/docs/installation.md) of how to configure both installation flags and environment variables would be useful.

**Comment by leipert** [comment]
I will add pull requests to atoms pathwatcher and runas with continous integration
It seems a little irresponsible that they only test OSX for pathwatcher and have no CI for runas :+1:

**Comment by Galadirith** [comment]
Great :dancer:

**Pull request merged**
