### PR TITLE
Fixed styles for Atom shadow deprecation

### PR DESCRIPTION
**Pull request by lucaskatayama**

### CODE REVIEW

**Comment by PeterTeng** [comment]
Is this pull request trying to solve the issue #242 ?

**Comment by lucaskatayama** [comment]
Yes..  But it fails on TravisCI and I don't know why...  

---- On Fri, 20 Jan 2017 02:16:03 -0200 notifications@github.com wrote ----

Is this pull request trying to solve the issue #242 ?

**Comment by dsernst** [comment]
@lucaskatayama Do these new CSS selectors work on your local machine?

**Comment by lucaskatayama** [comment]
@dsernst Yes... I'm using it. Now atom stopped with that deprecation warning.

**Comment by lierdakil** [comment]
No. there is no `.style--vertical-scrollbar` selector. Like, at all. Atom really has some stupid workarounds for `::shadow` selector removal...

So you just need to remove `::shadow` here. And also bump minimal engine version to 1.13. I'll try to reach @Galadirith to see if he'd be willing to add contributors or transfer project, and we'll try to get this merged.

Travis probably fails because tests are outdated, just ignore it for the time being.

**Comment by lierdakil** [comment]
Duplicate of #247, merged that instead.

**Pull request closed without merging**
